experiment:
    project: "MaskBit"
    name: "maskgit_tokenizer"
    max_train_examples: 1_281_167 # total number of imagenet examples
    vqgan_checkpoint: "MODEL_PATH/maskgit_tokenizer.bin"


model:
    vq_model:
        model_class: "maskgit"
        quantizer_type: "lookup"
        codebook_size: 1024
        token_size: 256
        commitment_cost: 0.25
        entropy_loss_weight: 0.02
        entropy_loss_temperature: 0.01
        entropy_gamma: 1.0
        num_channels: 3  # rgb
        hidden_channels: 128  # 64
        channel_mult: [1,1,2,2,4]
        num_resolutions: 5
        num_res_blocks: 2
        sample_with_conv: False

dataset:
    params:
        train_shards_path_or_url: "DATA_PATH/imagenet_shards/train/imagenet-train-{0000..0252}.tar"
        eval_shards_path_or_url: "DATA_PATH/imagenet_shards/val/imagenet-val-{0000..0009}.tar"
        shuffle_buffer_size: 1000
        num_workers_per_gpu: 8
        pin_memory: True
        persistent_workers: True
    preprocessing:
        resolution: 256
        use_aspect_ratio_aug: True
        use_random_crop: True
        min_scale: 0.8
        interpolation: "bilinear"


training:
    gradient_accumulation_steps: 1
    per_gpu_batch_size: 16
    mixed_precision: "no"  # "bf16"
    enable_tf32: True
    num_generated_images: 2  # Must be smaller than or equal to per_gpu_batch_size